#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=/opt/homebrew/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="/opt/homebrew/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_crud() {
    laravel_dir=${1}
    cd "${laravel_dir}" || exit 1
    echo
    bannerColor 'Installing CRUD.' "blue" "*"
    bannerColor 'CRUD: Running composer require backpack/crud:"4.1.*"' "blue" "*"
    composer require backpack/crud:"4.1.*" || exit 4
    echo
    bannerColor 'CRUD: Running composer require backpack/generators --dev' "blue" "*"
    composer require backpack/generators --dev || exit 4
    echo
    bannerColor 'CRUD: Running composer require laracasts/generators --dev' "blue" "*"
    composer require laracasts/generators --dev || exit 4
    echo
    bannerColor 'CRUD: Running php artisan backpack:install' "blue" "*"
    php artisan backpack:install || exit 4
    echo
    bannerColor 'CRUD installed.' "blue" "*"
}
