#!/usr/bin/env bash

# shellcheck disable=SC1091
source ./lib/banners

fn_crud() {
    laravel_dir=${1}
    cd "${laravel_dir}" || exit 1
    echo
    bannerColor 'Installing CRUD.' "blue" "*"
    bannerColor 'CRUD: Running composer require backpack/crud:"4.1.*"' "blue" "*"
    composer require backpack/crud:"4.1.*" || exit 4
    echo
    bannerColor 'CRUD: Running composer require backpack/generators --dev' "blue" "*"
    composer require backpack/generators --dev || exit 4
    echo
    bannerColor 'CRUD: Running composer require laracasts/generators --dev' "blue" "*"
    composer require laracasts/generators --dev || exit 4
    echo
    bannerColor 'CRUD: Running php artisan backpack:install' "blue" "*"
    php artisan backpack:install || exit 4
    echo
    bannerColor 'CRUD installed.' "blue" "*"
}
