#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_filemanager() {

    laravel_dir=$1
    cd "${laravel_dir}" || exit 1

    bannerColor "FILEMANAGER: Installing FileManager." "blue" "*"
    bannerColor 'FILEMANAGER: Running composer require backpack/filemanager' "blue" "*"
    composer require backpack/filemanager || exit 4
    echo
    bannerColor 'FILEMANAGER: Running php artisan backpack:filemanager:install' "blue" "*"
    php artisan backpack:filemanager:install || exit 4
    echo
    bannerColor 'FILEMANAGER: NewsCRUD installed.' "blue" "*"
}
