#!/usr/bin/env bash

# shellcheck disable=SC1091
source ./lib/banners

fn_filemanager() {

    laravel_dir=$1
    cd "${laravel_dir}" || exit 1

    bannerColor "FILEMANAGER: Installing FileManager." "blue" "*"
    bannerColor 'FILEMANAGER: Running composer require backpack/filemanager' "blue" "*"
    composer require backpack/filemanager || exit 4
    echo
    bannerColor 'FILEMANAGER: Running php artisan backpack:filemanager:install' "blue" "*"
    php artisan backpack:filemanager:install || exit 4
    echo
    bannerColor 'FILEMANAGER: NewsCRUD installed.' "blue" "*"
}
