#!/usr/bin/env bash
fn_logmanager() {

    source lib/banners
    laravel_dir=$1
    script_dir=$2
    cd "${laravel_dir}" || exit 1

    echo
    bannerColor "Installing LogManager." "blue" "*"
    echo
    bannerColor 'Running composer require backpack/logmanager' "blue" "*"
    echo
    composer require backpack/logmanager || exit 4
    echo
    bannerColor 'Adding storage to config/filesystems' "blue" "*"
    # Add a new "disk" to config/filesystems.php:
    sed -i "/'disks'/r ${script_dir}/disk_logmanager.txt" ./config/filesystems.php || exit 4
    echo
    # add APP_LOG=daily to .env
    bannerColor 'Adding APP_LOG,daily to config/app.php.' "blue" "*"
    sed -i "/return/r ${script_dir}/config_app_log.txt" ./config/app.php || exit 4
    echo
    bannerColor 'Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('log') }}'><i class='nav-icon la la-terminal'></i> Logs</a></li>" || exit 4

    # echo 'Replacing "channels" => ["single"]'
    # ORIGINAL_STRING="channels' => ['single'],"
    # NEW_STRING="channels' => ['daily'],"
    # FILENAME='config/logging.php'
    # sed -i "s/${ORIGINAL_STRING}/${NEW_STRING}/" $FILENAME || exit 4
    echo
    bannerColor "LogManager installed" "blue" "*"
}
