#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    sed=sed
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    sed=gsed
fi

# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_logmanager() {

    laravel_dir=$1
    script_dir=$2
    cd "${laravel_dir}" || exit 1

    echo
    bannerColor "LOGMANAGER: Installing LogManager." "blue" "*"
    bannerColor 'LOGMANAGER: Running composer require backpack/logmanager' "blue" "*"
    composer require backpack/logmanager || exit 4
    echo
    bannerColor 'LOGMANAGER: Adding storage to config/filesystems' "blue" "*"
    # Add a new "disk" to config/filesystems.php:
    $sed -i "/'disks'/r ${script_dir}/bp_files/disk_logmanager.txt" ${laravel_dir}/config/filesystems.php || exit 4
    echo
    # add APP_LOG=daily to .env
    bannerColor 'LOGMANAGER: Adding APP_LOG,daily to config/app.php.' "blue" "*"
    $sed -i "/return/r ${script_dir}/bp_files/config_app_log.txt" ${laravel_dir}/config/app.php || exit 4
    echo
    bannerColor 'LOGMANAGER: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('log') }}'><i class='nav-icon la la-terminal'></i> Logs</a></li>" || exit 4

    # echo 'Replacing "channels" => ["single"]'
    # ORIGINAL_STRING="channels' => ['single'],"
    # NEW_STRING="channels' => ['daily'],"
    # FILENAME='config/logging.php'
    # sed -i "s/${ORIGINAL_STRING}/${NEW_STRING}/" $FILENAME || exit 4
    echo
    bannerColor "LOGMANAGER: LogManager installed" "blue" "*"
}
