#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"
fn_menucrud() {

    laravel_dir=$1
    cd "${laravel_dir}" || exit 1

    bannerColor "MENUCRUD: Installing MenuCRUD." "blue" "*"
    echo
    bannerColor 'MENUCRUD: Running composer require backpack/menucrud' "blue" "*"
    composer require backpack/menucrud || exit 4
    echo
    bannerColor 'MENUCRUD: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Backpack\MenuCRUD\MenuCRUDServiceProvider" || exit 4
    echo
    bannerColor 'MENUCRUD: Running php artisan migrate' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'MENUCRUD: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('menu-item') }}'><i class='nav-icon la la-list'></i> <span>Menu</span></a></li>" || exit 4
    echo
    bannerColor 'MENUCRUD: MenuCRUD installed.' "blue" "*"
}
