#!/usr/bin/env bash
fn_menucrud() {

    cd "$1" || exit 1

    echo ">>>>> Installing MenuCRUD."
    echo
    echo '>>>>> Running composer require backpack/menucrud'
    composer require backpack/menucrud || exit 4
    echo
    echo '>>>>> Running php artisan vendor:publish --provider'
    php artisan vendor:publish --provider="Backpack\MenuCRUD\MenuCRUDServiceProvider" || exit 4
    echo
    echo '>>>>> Running php artisan migrate'
    php artisan migrate || exit 4
    echo
    echo '>>>>> Running php artisan backpack:add-sidebar-content'
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('menu-item') }}'><i class='nav-icon la la-list'></i> <span>Menu</span></a></li>" || exit 4
    echo
    echo '>>>>> MenuCRUD installed.'
}
