#!/usr/bin/env bash
fn_newscrud() {

    cd "$1" || exit 1

    echo ">>>>> Installing NewsCRUD."
    echo
    echo '>>>>> Running composer require backpack/newscrud'
    echo
    composer require backpack/newscrud || exit 4
    echo
    echo '>>>>> Running php artisan vendor:publish --provider'
    php artisan vendor:publish --provider="Backpack\NewsCRUD\NewsCRUDServiceProvider" || exit 4
    echo
    echo '>>>>> Running php artisan migrate'
    php artisan migrate || exit 4
    echo
    echo '>>>>> Running php artisan backpack:add-sidebar-content'
    php artisan backpack:add-sidebar-content "<li class='nav-item nav-dropdown'><a class='nav-link nav-dropdown-toggle' href='#'><i class='nav-icon la la-newspaper-o'></i>News</a><ul class='nav-dropdown-items'><li class='nav-item'><a class='nav-link' href='{{ backpack_url('article') }}'><i class='nav-icon la la-newspaper-o'></i> Articles</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('category') }}'><i class='nav-icon la la-list'></i> Categories</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('tag') }}'><i class='nav-icon la la-tag'></i> Tags</a></li></ul></li>" || exit 4
    echo
    echo '>>>>> NewsCRUD installed.'
}
