#!/usr/bin/env bash

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(realpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_newscrud() {

    laravel_dir=$1
    cd "${laravel_dir}" || exit 1

    bannerColor "NEWSCRUD: Installing NewsCRUD." "blue" "*"
    echo
    bannerColor 'NEWSCRUD: Running composer require backpack/newscrud' "blue" "*"
    echo
    composer require backpack/newscrud || exit 4
    echo
    bannerColor 'NEWSCRUD: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Backpack\NewsCRUD\NewsCRUDServiceProvider" || exit 4
    echo
    bannerColor 'NEWSCRUD: Running php artisan migrate' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'NEWSCRUD: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item nav-dropdown'><a class='nav-link nav-dropdown-toggle' href='#'><i class='nav-icon la la-newspaper-o'></i>News</a><ul class='nav-dropdown-items'><li class='nav-item'><a class='nav-link' href='{{ backpack_url('article') }}'><i class='nav-icon la la-newspaper-o'></i> Articles</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('category') }}'><i class='nav-icon la la-list'></i> Categories</a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('tag') }}'><i class='nav-icon la la-tag'></i> Tags</a></li></ul></li>" || exit 4
    echo
    bannerColor 'NEWSCRUD: NewsCRUD installed.' "blue" "*"
}
