#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_permissionmanager() {

    laravel_dir=$1
    script_dir=$2
    cd "${laravel_dir}" || exit 1

    echo
    bannerColor "PERMISSIONMANAGER: Installing PermissionManager." "blue" "*"
    echo
    bannerColor 'PERMISSIONMANAGER: Running composer require backpack/permissionmanager' "blue" "*"
    composer require backpack/permissionmanager || exit 4
    echo
    bannerColor 'PERMISSIONMANAGER: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations" || exit 4
    echo
    bannerColor 'PERMISSIONMANAGER: Running php artisan migrate' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'PERMISSIONMANAGER: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
    echo
    bannerColor 'PERMISSIONMANAGER: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider" --tag="config" || exit 4
    echo
    bannerColor 'PERMISSIONMANAGER: Running the migraions: ' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'PERMISSIONMANAGER: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<!-- Users, Roles, Permissions --><li class='nav-item nav-dropdown'><a class='nav-link nav-dropdown-toggle' href='#'><i class='nav-icon la la-users'></i> Authentication</a><ul class='nav-dropdown-items'><li class='nav-item'><a class='nav-link' href='{{ backpack_url('user') }}'><i class='nav-icon la la-user'></i> <span>Users</span></a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('role') }}'><i class='nav-icon la la-id-badge'></i> <span>Roles</span></a></li><li class='nav-item'><a class='nav-link' href='{{ backpack_url('permission') }}'><i class='nav-icon la la-key'></i> <span>Permissions</span></a></li></ul></li>"
    echo
    bannerColor 'PERMISSIONMANAGER: Changing App\Models\User.' "blue" "*"
    cp "${script_dir}"/bp_files/User.php "${laravel_dir}"/app/Models/User.php
    bannerColor 'PERMISSIONMANAGER: PermissionManager installed.' "blue" "*"
}
