#!/usr/bin/env bash

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

which_install=$(which backpack_install)

if [[ -L $which_install ]]; then
    # check if installation is Homebrew
    # if so use script_dir=$(brew --prefix)/Cellar/backpack_install/${version}/bin
    if [[ "$which_install" == *"homebrew"* ]]; then
        script_dir="$(brew --prefix)/Cellar/backpack_install/${version}/bin"
    else
        link=$(myrealpath "${which_install}")
        script_dir=$(dirname "${link}")
    fi
else
    script_dir="./"
fi
# shellcheck disable=SC1091
source "${script_dir}/lib/banners"

fn_pagemanager() {

    laravel_dir=$1
    script_dir=$2
    cd "${laravel_dir}" || exit 1

    echo
    bannerColor "PAGEMANAGER: Installing PageManager." "blue" "*"
    echo
    bannerColor 'PAGEMANAGER: Adding app/PageTemplates.php' "blue" "*"
    pagetemp=./app/PageTemplates.php
    if [[ ! -e $pagetemp ]]; then
        cp "$script_dir"/bp_files/PageTemplates.php "$laravel_dir"/app
    fi
    echo
    bannerColor 'PAGEMANAGER: Running composer require backpack/pagemanager' "blue" "*"
    composer require backpack/pagemanager || exit 4
    echo
    bannerColor 'PAGEMANAGER: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Backpack\PageManager\PageManagerServiceProvider" || exit 4
    echo
    bannerColor 'PAGEMANAGER: Running php artisan migrate' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'PAGEMANAGER: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('page') }}'><i class='nav-icon la la-file-o'></i> <span>Pages</span></a></li>" || exit 4
    echo
    bannerColor 'PAGEMANAGER: PageManager installed' "blue" "*"
}
