#!/usr/bin/env bash

# shellcheck disable=SC1091
source ./lib/banners

fn_settings() {

    laravel_dir=$1
    cd "${laravel_dir}" || exit 1

    echo
    bannerColor "SETTINGS: Installing Settings." "blue" "*"
    bannerColor 'SETTINGS: Running composer require backpack/settings' "blue" "*"
    composer require backpack/settings || exit 4
    echo
    bannerColor 'SETTINGS: Running php artisan vendor:publish --provider' "blue" "*"
    php artisan vendor:publish --provider="Backpack\Settings\SettingsServiceProvider" || exit 4
    echo
    bannerColor 'SETTINGS: Running php artisan migrate' "blue" "*"
    php artisan migrate || exit 4
    echo
    bannerColor 'SETTINGS: Running php artisan backpack:add-sidebar-content' "blue" "*"
    php artisan backpack:add-sidebar-content "<li class='nav-item'><a class='nav-link' href='{{ backpack_url('setting') }}'><i class='nav-icon la la-cog'></i> <span>Settings</span></a></li>" || exit 4
    echo
    bannerColor 'SETTINGS: Running php artisan db:seed --class' "blue" "*"
    php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder" || exit 4
    echo
    bannerColor "SETTINGS: Settings installed" "blue" "*"
}
